version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching in containers
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate pseudo-TTY
